---
version: '2'
services:
  vault-server:
    image: vault
    cap_add:
    - IPC_LOCK
    ports:
      - "8200:8200"
    command: ["server"]
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "true"}}}'
  vault-client:
    image: vault
    links:
      - vault-server
    entrypoint: ["sh", "-c", "sleep 2 && vault init; tail -f /dev/null"]
    environment:
      VAULT_ADDR: http://vault-server:8200
  vault-unsealer-first:
    build: .
    entrypoint: ["sh", "-c", "sleep 4 && go-wrapper run -server"]
    ports:
      - "8443:443"
    links:
      - vault-server
    volumes:
      - ./artifacts:/artifacts
      - .:/app
    environment:
      HTTPS_CERT: /artifacts/dev-cert.pem
      HTTPS_CERT_KEY: /artifacts/dev-key.pem
      LISTEN_ADDR: 0.0.0.0:443
      VAULT_ADDR: http://vault-server:8200
      ROOT_TOKEN_TEST: "true"
  vault-unsealer-second:
    build: .
    entrypoint: ["sh", "-c", "sleep 4 && go-wrapper run -server"]
    ports:
      - "8444:443"
    links:
      - vault-server
    volumes:
      - ./artifacts:/artifacts
      - .:/app
    environment:
      HTTPS_CERT: /artifacts/dev-cert.pem
      HTTPS_CERT_KEY: /artifacts/dev-key.pem
      LISTEN_ADDR: 0.0.0.0:443
      VAULT_ADDR: http://vault-server:8200
      ROOT_TOKEN_TEST: "true"